steps:
- name: Hub Mirror Action.
  uses: Yikun/hub-mirror-action@v1.2
  with:
    src: github/KilluaAoki
    dst: gitee/KilluaAoki
    dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    dst_token: ${{ secrets.GITEE_TOKEN }}
    account_type: user
    force_update: true
    clone_style: "ssh"

