name: Sync Github Repos To Gitee

on:
  schedule:
    - cron: "1 17 * * *"

jobs:
  run:
    name: Sync GitHub to Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Get current repository name
        id: info
        uses: actions/github-script@v3.1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            return context.repo.repo;

      - name: Mirror the GitHub repos to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/KilluaAoki
          dst: gitee/KilluaAoki
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "${{ steps.info.outputs.result }}"
          account_type: user
          force_update: true
          # clone_style: "ssh"
          # debug: false
          # timeout: 300
